### ISSUE TITLE
Set  error  Dangerous property 'dangerouslySetInnerHTML' found  react/no-danger as warning

### ISSUE THREAD

**Issue by tdurand** [TechChange/eslint-config#7]
I let you do it as i haven't been working on eslint config

**Comment by wchest** [comment]
@tdurand - awesome, thanks creating this. After thinking about this more, I'm actually a bit torn. If we make this a warning, it means that we'll always have warnings whenever it's used, unless you turn it off through the comments. At the same time, if you turn it off through comments, we might as well keep it an error because it won't be triggered anyway.

So, my new suggestion would be one of two options:
1. Keep it an error and use commenting to disable it when necessary
2. Remove the rule altogether because if it's going to be used in our code and can't reasoned about programmatically it may need to be a convention rather than a requirement.

Thoughts?

**Comment by tdurand** [comment]
i would remove the rule

**Comment by tdurand** [comment]
the name of the method, dangerouslySetInnerHTML is enought to warn us of what we are doing

**Comment by wchest** [comment]
@tdurand - haha, very good point.
